version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: restaurant-pos-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: restaurant-pos
    volumes:
      - mongodb_data:/data/db
      - ./tools/database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - restaurant-pos-network

  redis:
    image: redis:7.2-alpine
    container_name: restaurant-pos-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass "redis123"
    volumes:
      - redis_data:/data
    networks:
      - restaurant-pos-network

  # Optional: Database Admin UI
  mongo-express:
    image: mongo-express:latest
    container_name: restaurant-pos-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - restaurant-pos-network

volumes:
  mongodb_data:
  redis_data:

networks:
  restaurant-pos-network:
    driver: bridge